#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"

# start some nice programs
eval $(ssh-agent)
MONITOR=$(/usr/bin/xrandr | /usr/bin/grep connected | /usr/bin/grep -v disconnected | /usr/bin/grep -v eDP1 | /usr/bin/awk '{print $1}')
VAR='GNU/Linux is an operating system'
if [[ $MONITOR == "eDP1" ]]; then
	xrandr --newmode 1920x1200_60 154 1920 1968 2000 2080 1200 1203 1209 1235 -hsync +vsync
	xrandr --addmode eDP1 1920x1200_60
	xrandr --output eDP1 --mode 1920x1200_60
fi
sh ~/.config/polybar/launch.sh &
sh ~/.config/i3/reset.sh

test $(which xsetroot)  && xsetroot -solid midnightblue &
test $(which gpg-agent) && eval $(gpg-agent --daemon)

if [ $(which xbanish) ]; then
    xbanish >>$HOME/.xbanish.log &    # https://github.com/jcs/xbanish
elif [ $(which unclutter) ]; then
    unclutter &
fi

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"


/usr/local/bin/dwm 2>>.dwm_log &

# exit X when dwmstatus (or failsafe xterm) is killed
if [ $(which kitty) ]; then
    kitty
if [ $(which alacritty) ]; then
    alacritty
if [ $(which slstatus) ]; then
    slstatus
elif [ $(which dwmstatus) ]; then
    dwmstatus
elif [ $(which st) ]; then
    st
elif [ $(which urxvt) ]; then
    urxvt
elif [ $(which uxterm) ]; then
    uxterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which rxvt) ]; then
    rxvt
elif [ $(which xterm) ]; then
    xterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which gnome-terminal) ]; then
    gnome-terminal
fi
